### ISSUE TITLE
Types for Structs with Serde Field Attributes

### ISSUE THREAD

**Issue by thekeviv** [kevinheavey/solders#40]
Hi,
I am trying to port over some code from Typescript to Python and I want to use the types provided by this library for it (the Solana RPC response types). In web3.js, there is a [ParsedTransactionWithMeta](https://solana-labs.github.io/solana-web3.js/types/ParsedTransactionWithMeta.html) type which is used in methods like [getParsedTransaction](https://solana-labs.github.io/solana-web3.js/types/ParsedTransactionWithMeta.html). This is the `getTransaction` rpc method with encoding set to `jsonParsed`. I wanted a type corresponding to it in Python. 

This library has a [GetTransactionResp](https://github.com/michaelhly/solana-py/blob/094d24bb035ddf24d8a61a1b7bd5e4709553cdcb/src/solana/rpc/api.py#L52) type however that is a bit different from the data I get back.

I took a look at the Solana code which that method calls to fetch data. The type for the data returned for jsonParsed encoding is [EncodedConfirmedTransactionWithStatusMeta](https://github.com/solana-labs/solana/blob/3bd389149cbb40f5eb3030b8eb66daab77b4e2a0/transaction-status/src/lib.rs#L1019) as also in the value param in the library [here](https://github.com/kevinheavey/solders/blob/main/python/solders/rpc/responses.pyi#L1349). However, that Rust struct has `#[serde(flatten)]` field attribute on transaction and so in the data returned from rpc (or web3), that type gets flattened. This unfortunately leads to a difference between the type provided in this library and the one corresponding to the data. I think I've seem code in the past here where they rename certain fields too so this could have impact there too.

Can I do anything about this? Any help will be very appreciated.

Thank you for your hard work!

**Comment by kevinheavey** [comment]
Do you have a reproducible example?

**Comment by thekeviv** [comment]
Hi, here's a quick example I wrote to show this:

1. First I make a call using the regular RPC API and I get this response. This is the same output I get from the web3.js library in Typescript too.
<img width="683" alt="Screenshot 2023-01-27 at 11 08 00 AM" src="https://user-images.githubusercontent.com/16347985/215177623-ac569a34-b5d1-4e93-b1e0-e1b53037ee0b.png">. 

2. Then I make the same call using your [Solana library](https://michaelhly.github.io/solana-py/) and notice how the output is slightly different despite passing the same params. In the output, transaction isn't flattened with meta, version and transaction being nested inside another transaction key. 
<img width="1164" alt="Screenshot 2023-01-27 at 11 11 51 AM" src="https://user-images.githubusercontent.com/16347985/215179531-0efe6acc-8160-41f0-81ed-c75e27a33d8b.png">

I was expecting similar outputs between RPC, Web3.js and the Python library. 

In web3.js, what they have done is to create 2 different methods, 1 for `getTransaction` which runs with regular encoding and returns a transaction like it did in 2. Then there's a getParsedTransaction which returns it in a format similar to 1 (with the parsing applied).

**Comment by kevinheavey** [comment]
Ah I see, thanks. We parse the getTransaction response the [same way](https://docs.rs/solana-client/latest/solana_client/nonblocking/rpc_client/struct.RpcClient.html#method.get_transaction) the Solana Rust client does. This is really about solana_client and web3.js differing.

**Comment by thekeviv** [comment]
I see. I think I'll create a type myself with the flattened structure reusing the other types provided by solders. I'll close this issue accordingly. 

Thank you for your response.
