### ISSUE TITLE
Unable to import metaplex metadata program PublicKey

### ISSUE THREAD

**Issue by GabrielePicco** [kevinheavey/solders#46]
Hi, I'm unable to import the metaplex metadata program PublicKey

## How to reproduce

```
from solders.pubkey import Pubkey
Pubkey("metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s")
```

Error:

`ValueError: expected a sequence of length 32 (got 43)`

**Comment by kevinheavey** [comment]
This is because you should use Pubkey.from_string for this. Btw I strongly recommend running a type checker such as mypy 😅

**Comment by GabrielePicco** [comment]
Makes total sense, thanks. Closing as not relevant.

**Comment by GabrielePicco** [comment]
@kevinheavey some of the examples in the anchorpy documentation may be outdated, I noticed that some don't use Pubkey.from_string. I will open a PR.
