### ISSUE TITLE
Potential error in getter function pre_token_balances?

### ISSUE THREAD

**Issue by grantgittes** [kevinheavey/solders#55]
https://github.com/kevinheavey/solders/blob/bffc0df1c6086d7d6a2475275ef865198f31d6cb/crates/transaction-status/src/lib.rs#L918

Seems like the getter function is referencing post_token_balance for the pre_token_balances function?

**Comment by kevinheavey** [comment]
Yes this is definitely a mistake. Happy to accept a PR, otherwise will take a look when I'm done travelling

**Comment by kevinheavey** [comment]
Closed by #59
