### ISSUE TITLE
Feature Request: HD Wallet Support

### ISSUE THREAD

**Issue by hkey0** [kevinheavey/solders#68]
Hello, Solders caregivers,

I am currently using the Solders library to manage wallets and signatures in Solana. I have found the library to be extremely useful for my needs. However, there is one feature that I believe could significantly improve its functionality: HD Wallet support.

**Feature Description:**
HD Wallets provide a more secure and organized way to manage multiple addresses and keys. With HD Wallets, users can create an address tree from a single seed, which makes it easier to manage a large number of addresses and increases security by enabling different addresses to be used for different transactions.

This feature will make it easier to transfer the wallets we have created to other wallets. Normally I would like to add this feature, but due to my busy schedule, I can't do it right now, so I decided to create this issue in case someone is interested. 

Thank you for considering this feature request. I look forward to any discussion or feedback on this proposal.

Best regards.

**Comment by kevinheavey** [comment]
Think we just need a wrapper for this function? https://docs.rs/sol-chainsaw/latest/sol_chainsaw/solana_sdk/signature/keypair/fn.keypair_from_seed_and_derivation_path.html

**Comment by hkey0** [comment]
> Think we just need a wrapper for this function? https://docs.rs/sol-chainsaw/latest/sol_chainsaw/solana_sdk/signature/keypair/fn.keypair_from_seed_and_derivation_path.html

This looks like it will definitely work

**Comment by kevinheavey** [comment]
Closed by #75
