### ISSUE TITLE
Not recognizing Pubkey in Python. 

### ISSUE THREAD

**Issue by aaroncatalano** [kevinheavey/solders#77]
What versions does your solders library support?

Environment:  
Python 3.10
solana-cli 1.17
solana==0.30.2
httpx==0.23.0  
solders .19
python-telegram-bot==13

Telegram python bot script does not recognize 
from solders.pubkey import Pubkey.     Import "solders.pubkey" could not be resolved from source

 I have dependencies on   :

    # Verify the signed message
    try:
        username, phantom_wallet_address = signed_message.strip().split(' ', 1)  # Limit the split to 1 occurrence
        if Pubkey.verify(username.encode("utf-8"), signed_message, Pubkey(phantom_wallet_address)):

**Comment by kevinheavey** [comment]
Does `import solders` give an error?

**Comment by aaroncatalano** [comment]
Import "solders.pubkey" could not be resolved from source.    AttributeError: type object 'solders.pubkey.Pubkey' has no attribute 'verify'

**Comment by kevinheavey** [comment]
Oh there's no Pubkey.verify method. There's a Signature.verify which is probably what you're looking for https://kevinheavey.github.io/solders/api_reference/signature.html#solders.signature.Signature.verify

Does something somewhere say there is a Pubkey.verify?

**Comment by aaroncatalano** [comment]
from solders.pubkey import Pubkey.    Error: Import "solders.pubkey" could not be resolved from source.  The Pubkey is not being imported from solders.pubkey.

**Comment by kevinheavey** [comment]
Does `import solders` give an error?

**Comment by aaroncatalano** [comment]
Import "solders.keypair" could not be resolved from sourcePylance[reportMissingModuleSource](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingModuleSource)
(module) solders

**Comment by kevinheavey** [comment]
Ok but that's just a Pylance error. What happens when you actually run the code?

**Comment by aaroncatalano** [comment]
Is solders compatible with: Python 3.10
solana-cli 1.17
solana==0.30.2?   //  

def verify_wallet(update, context):
try:
    username, phantom_wallet_address = signed_message.strip().split(' ', 1)  # Limit the split to 1 occurrence
    if Pubkey.verify(username.encode("utf-8"), signed_message, Pubkey(phantom_wallet_address)):    

 Error Message:  AttributeError: type object 'solders.pubkey.Pubkey' has no attribute 'verify'
2024-01-21 17:25:27,771 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File local/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 557, in process_update
    handler.handle_update(update, self, check, context)
  File /.local/lib/python3.10/site-packages/telegram/ext/handler.py", line 199, in handle_update
    return self.callback(update, context)
  File bot/bot6.py", line 122, in verify_wallet
    if Pubkey.verify(username.encode("utf-8"), signed_message, Pubkey(phantom_wallet_address)):

**Comment by kevinheavey** [comment]
Can you please communicate better

**Comment by aaroncatalano** [comment]
Is solders compatible with: Python 3.10
solana-cli 1.17
solana==0.30.2?   //

**Comment by kevinheavey** [comment]
This is not what a good GitHub issue looks like

**Comment by aaroncatalano** [comment]
Your solders library.  From solders.pubkey import Pubkey., does not support  Verify function?                                                  
from solders.pubkey import Pubkey   def verify_wallet(update, context):
try:
username, phantom_wallet_address = signed_message.strip().split(' ', 1) # Limit the split to 1 occurrence
if Pubkey.verify(username.encode("utf-8"), signed_message, Pubkey(phantom_wallet_address)):

**Comment by kevinheavey** [comment]
Please read https://github.com/kevinheavey/solders/issues/77#issuecomment-1902785061
