### ISSUE TITLE
from solders.pubkey import Pubkey

### ISSUE THREAD

**Issue by MarianoAkaMery** [kevinheavey/solders#78]
i'm not able to use from solders.pubkey import Pubkey

any reason why'

I installed it using **_pip install solders_**

**Comment by kevinheavey** [comment]
What error message do you get?

**Comment by MarianoAkaMery** [comment]
![image](https://github.com/kevinheavey/solders/assets/42919644/678397fe-4468-4697-8c82-277dee804899)



I just don't get any library when installing it

**Comment by MarianoAkaMery** [comment]
pip install solders
Requirement already satisfied: solders in c:\users\mariano\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (0.19.0)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\mariano\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from solders) (4.8.0)
Requirement already satisfied: jsonalias==0.1.1 in c:\users\mariano\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from solders) (0.1.1)

**Comment by kevinheavey** [comment]
Is the error just in vscode? When you run the code does it run fine? There's a problem with Pylance where it complains about not being able to find Python source files (because there are none), but otherwise works properly

**Comment by MarianoAkaMery** [comment]
WebSocket error: String is the wrong size


ok yes is working, idkn why when copy and paste a public key or something it gets decoded by something, literally need to type manual adress and don't know why ahaha


but yeah it works
