### ISSUE TITLE
Transaction serialize not found

### ISSUE THREAD

**Issue by jasonthewhale** [kevinheavey/solders#89]
I met this error when calling [send_bundle](https://github.com/jito-labs/jito-python/blob/master/jito_searcher_client/examples/searcher-cli.py#L159) of jito-python library.
    data=tx.serialize(),
         ^^^^^^^^^^^^
AttributeError: 'solders.transaction.Transaction' object has no attribute 'serialize'

Do we actually have a function to serialize Transaction class?

**Comment by kevinheavey** [comment]
To serialize a solders transaction, just call `bytes(tx)`
