### ISSUE TITLE
How do I load keypair in my phantom wallet

### ISSUE THREAD

**Issue by satwikkansal** [kevinheavey/solders#92]
```py
# generate random keypair
keypair = Keypair()
secret = keypair.secret()
```

Now how do I use this secret to get a private key that I can import into my Phantom wallet?

I tried using b58encode but it doesn't work, I'm sure I'm missing something silly but not sure what

**Comment by kevinheavey** [comment]
I'm not sure what phantom wants but based on [these docs](https://help.phantom.app/hc/en-us/articles/15079894392851-Importing-Your-Existing-Wallet-into-Phantom) my guess is either `str(keypair)` or `str(secret)`

**Comment by satwikkansal** [comment]
Thanks, `str(keypair)` works!
