### ISSUE TITLE
is bankrun currently not bundled in?

### ISSUE THREAD

**Issue by ff781** [kevinheavey/solders#97]
i see bankrun is trying to get imported in the solder's __init__, but the bankrun import fails, even though i see the crate fully implemented in the source code. is that intended?

**Comment by kevinheavey** [comment]
It's not included on platforms where it doesn't work. What platform are you using?

**Comment by ff781** [comment]
windows :(

**Comment by ff781** [comment]
does it only work on unix systems?

**Comment by kevinheavey** [comment]
Unix and Mac. The underlying Solana Rust libraries don't work on Windows unfortunately. If one day they do I'll add Windows support to Bankrun
